# Generated by Django 4.2.2 on 2023-06-11 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Covidians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, null=True)),
                ("email", models.CharField(max_length=64, null=True, unique=True)),
                (
                    "tested_positive",
                    models.CharField(default="YES", max_length=3, null=True),
                ),
                ("shots_taken", models.PositiveIntegerField(default=0)),
                (
                    "user_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user_photo",
                    models.ImageField(blank=True, null=True, upload_to="my_media"),
                ),
            ],
        ),
    ]
