# Generated by Django 4.2.2 on 2023-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_web", "0002_alter_covidians_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
